### ISSUE TITLE
Price stored in double

### ISSUE THREAD

**Issue by joshua-kfbb** [sergeysachkov/Corrigan-s-Supermarket#20]
In item model prices are stored in double. Due to the precision of double, some price calculation will give ridiculous result.
![image](https://cloud.githubusercontent.com/assets/22837904/22647691/ec859a5e-ec6a-11e6-98ea-a9ae3b1b34f9.png)

**Comment by sergeysachkov** [comment]
format the result, with precision of .2f

**Comment by joshua-kfbb** [comment]
result formatted in #21

**Comment by sergeysachkov** [comment]
thank you
